package fun.slikdlc.api.storages.implement.helpertstorages.enumvar;

import fun.slikdlc.client.modules.impl.combat.AimBot;
import fun.slikdlc.client.modules.impl.combat.AntiBot;
import fun.slikdlc.client.modules.impl.combat.Aura;
import fun.slikdlc.client.modules.impl.combat.AutoExplosion;
import fun.slikdlc.client.modules.impl.combat.AutoSwap;
import fun.slikdlc.client.modules.impl.combat.AutoTotem;
import fun.slikdlc.client.modules.impl.combat.AutoTrap;
import fun.slikdlc.client.modules.impl.combat.ElytraMotion;
import fun.slikdlc.client.modules.impl.combat.ElytraResolver;
import fun.slikdlc.client.modules.impl.combat.ElytraTarget;
import fun.slikdlc.client.modules.impl.combat.ItemRelease;
import fun.slikdlc.client.modules.impl.combat.NoControllerWeb;
import fun.slikdlc.client.modules.impl.combat.NoVelocity;
import fun.slikdlc.client.modules.impl.combat.PacketCriticals;
import fun.slikdlc.client.modules.impl.combat.TpsSync;
import fun.slikdlc.client.modules.impl.combat.TriggerBot;
import fun.slikdlc.client.modules.impl.misc.AutoAccept;
import fun.slikdlc.client.modules.impl.misc.AutoBrew;
import fun.slikdlc.client.modules.impl.misc.AutoBuy;
import fun.slikdlc.client.modules.impl.misc.AutoDuel;
import fun.slikdlc.client.modules.impl.misc.AutoJoin;
import fun.slikdlc.client.modules.impl.misc.AutoLeave;
import fun.slikdlc.client.modules.impl.misc.AutoPvp;
import fun.slikdlc.client.modules.impl.misc.ClickPearl;
import fun.slikdlc.client.modules.impl.misc.ClientSounds;
import fun.slikdlc.client.modules.impl.misc.DeathCoord;
import fun.slikdlc.client.modules.impl.misc.EcOpen;
import fun.slikdlc.client.modules.impl.misc.ElytraSwap;
import fun.slikdlc.client.modules.impl.misc.KeyStrokes;
import fun.slikdlc.client.modules.impl.misc.LeaveTracker;
import fun.slikdlc.client.modules.impl.misc.NameProtect;
import fun.slikdlc.client.modules.impl.misc.ScoreboardHP;
import fun.slikdlc.client.modules.impl.misc.ServerHelper;
import fun.slikdlc.client.modules.impl.misc.TpLoot;
import fun.slikdlc.client.modules.impl.misc.XCarry;
import fun.slikdlc.client.modules.impl.movement.AirStuck;
import fun.slikdlc.client.modules.impl.movement.AutoJump;
import fun.slikdlc.client.modules.impl.movement.ElytraBoost;
import fun.slikdlc.client.modules.impl.movement.Flight;
import fun.slikdlc.client.modules.impl.movement.FreeCam;
import fun.slikdlc.client.modules.impl.movement.GrimGlide;
import fun.slikdlc.client.modules.impl.movement.GrimNoFall;
import fun.slikdlc.client.modules.impl.movement.HighJump;
import fun.slikdlc.client.modules.impl.movement.InventoryWalk;
import fun.slikdlc.client.modules.impl.movement.NoSlow;
import fun.slikdlc.client.modules.impl.movement.NoWeb;
import fun.slikdlc.client.modules.impl.movement.PlayerFakeLags;
import fun.slikdlc.client.modules.impl.movement.Speed;
import fun.slikdlc.client.modules.impl.movement.Spider;
import fun.slikdlc.client.modules.impl.movement.Sprint;
import fun.slikdlc.client.modules.impl.movement.Step;
import fun.slikdlc.client.modules.impl.movement.Timer;
import fun.slikdlc.client.modules.impl.movement.TpBack;
import fun.slikdlc.client.modules.impl.player.AutoArmor;
import fun.slikdlc.client.modules.impl.player.AutoEat;
import fun.slikdlc.client.modules.impl.player.AutoFish;
import fun.slikdlc.client.modules.impl.player.AutoForest;
import fun.slikdlc.client.modules.impl.player.AutoTool;
import fun.slikdlc.client.modules.impl.player.ChestStealer;
import fun.slikdlc.client.modules.impl.player.FastBreak;
import fun.slikdlc.client.modules.impl.player.FastExp;
import fun.slikdlc.client.modules.impl.player.HelpMessage;
import fun.slikdlc.client.modules.impl.player.ItemAim;
import fun.slikdlc.client.modules.impl.player.ItemScroller;
import fun.slikdlc.client.modules.impl.player.KTLeave;
import fun.slikdlc.client.modules.impl.player.LockSlot;
import fun.slikdlc.client.modules.impl.player.NoClip;
import fun.slikdlc.client.modules.impl.player.NoJumpDelay;
import fun.slikdlc.client.modules.impl.player.NoPush;
import fun.slikdlc.client.modules.impl.player.Nuker;
import fun.slikdlc.client.modules.impl.player.TargetPearl;
import fun.slikdlc.client.modules.impl.render.Arrows;
import fun.slikdlc.client.modules.impl.render.BeautifulHands;
import fun.slikdlc.client.modules.impl.render.BlockESP;
import fun.slikdlc.client.modules.impl.render.BlockOverlay;
import fun.slikdlc.client.modules.impl.render.Cosmetics;
import fun.slikdlc.client.modules.impl.render.Cubes;
import fun.slikdlc.client.modules.impl.render.EntityESP;
import fun.slikdlc.client.modules.impl.render.FireworkESP;
import fun.slikdlc.client.modules.impl.render.FullBright;
import fun.slikdlc.client.modules.impl.render.HitBubbles;
import fun.slikdlc.client.modules.impl.render.HitMarker;
import fun.slikdlc.client.modules.impl.render.Interface;
import fun.slikdlc.client.modules.impl.render.InterpolateF5;
import fun.slikdlc.client.modules.impl.render.JumpCircle;
import fun.slikdlc.client.modules.impl.render.KillEffect;
import fun.slikdlc.client.modules.impl.render.LineGlyphes;
import fun.slikdlc.client.modules.impl.render.LootTracker;
import fun.slikdlc.client.modules.impl.render.NoVignette;
import fun.slikdlc.client.modules.impl.render.Particle;
import fun.slikdlc.client.modules.impl.render.Projectile;
import fun.slikdlc.client.modules.impl.render.RPSpoofer;
import fun.slikdlc.client.modules.impl.render.Removals;
import fun.slikdlc.client.modules.impl.render.Satellite;
import fun.slikdlc.client.modules.impl.render.SeeInvisibles;
import fun.slikdlc.client.modules.impl.render.ShaderEsp;
import fun.slikdlc.client.modules.impl.render.ShaderHands;
import fun.slikdlc.client.modules.impl.render.ShulkerPreview;
import fun.slikdlc.client.modules.impl.render.Sonar;
import fun.slikdlc.client.modules.impl.render.SwingAnimations;
import fun.slikdlc.client.modules.impl.render.TargetESP;
import fun.slikdlc.client.modules.impl.render.TotemAngel;
import fun.slikdlc.client.modules.impl.render.Trails;
import fun.slikdlc.client.modules.impl.render.Trajectories;
import fun.slikdlc.client.modules.impl.render.ViewModel;
import fun.slikdlc.client.modules.impl.render.WorldTweaks;

public interface ModuleRewords {
   AirStuck airStuck = AirStuck.INSTANCE;
   Arrows arrows = Arrows.INSTANCE;
   Aura aura = Aura.INSTANCE;
   AntiBot antibot = AntiBot.INSTANCE;
   AutoAccept autoAccept = AutoAccept.INSTANCE;
   AutoArmor autoArmor = AutoArmor.INSTANCE;
   AutoFish autoFish = AutoFish.INSTANCE;
   AutoForest autoForest = AutoForest.INSTANCE;
   DeathCoord deathCoord = DeathCoord.INSTANCE;
   LeaveTracker leavetracker = LeaveTracker.INSTANCE;
   EcOpen ecopen = EcOpen.INSTANCE;
   AutoBuy autoBuy = AutoBuy.INSTANCE;
   AutoDuel autoDuel = AutoDuel.INSTANCE;
   AutoEat autoEat = AutoEat.INSTANCE;
   AutoLeave autoLeave = AutoLeave.INSTANCE;
   AutoExplosion autoExplosion = AutoExplosion.INSTANCE;
   AutoJoin autoJoin = AutoJoin.INSTANCE;
   AutoPvp autoPvp = AutoPvp.INSTANCE;
   NameProtect nameProtect = NameProtect.INSTANCE;
   AutoJump autoJump = AutoJump.INSTANCE;
   ChestStealer chestStealer = ChestStealer.INSTANCE;
   ClientSounds clientSounds = ClientSounds.INSTANCE;
   AutoTool autoTool = AutoTool.INSTANCE;
   AutoTotem autoTotem = AutoTotem.INSTANCE;
   AutoTrap autoTrap = AutoTrap.INSTANCE;
   BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
   ClickPearl clickPearl = ClickPearl.INSTANCE;
   Cosmetics cosmetics = Cosmetics.INSTANCE;
   Cubes cubes = Cubes.INSTANCE;
   KeyStrokes keyStrokes = KeyStrokes.INSTANCE;
   KillEffect killEffect = KillEffect.INSTANCE;
   BlockESP blockesp = BlockESP.INSTANCE;
   ElytraBoost elytraBoost = ElytraBoost.INSTANCE;
   ElytraMotion elytraMotion = ElytraMotion.INSTANCE;
   ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
   ElytraTarget elytraTarget = ElytraTarget.INSTANCE;
   ElytraResolver elytraresolver = ElytraResolver.INSTANCE;
   EntityESP entityESP = EntityESP.INSTANCE;
   Flight flight = Flight.INSTANCE;
   FreeCam freeCam = FreeCam.INSTANCE;
   FullBright fullBright = FullBright.INSTANCE;
   GrimNoFall grimNoFall = GrimNoFall.INSTANCE;
   GrimGlide grimGlide = GrimGlide.INSTANCE;
   HighJump highJump = HighJump.INSTANCE;
   HelpMessage helpMessage = HelpMessage.INSTANCE;
   HitBubbles hitBubbles = HitBubbles.INSTANCE;
   Interface interfaceModule = Interface.INSTANCE;
   InterpolateF5 interpolateF5 = InterpolateF5.INSTANCE;
   InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
   ItemAim itemAim = ItemAim.INSTANCE;
   ItemScroller itemScroller = ItemScroller.INSTANCE;
   ItemRelease itemRelease = ItemRelease.INSTANCE;
   JumpCircle jumpCircle = JumpCircle.INSTANCE;
   KTLeave kTLeave = KTLeave.INSTANCE;
   LineGlyphes lineGlyphes = LineGlyphes.INSTANCE;
   LockSlot lockSlot = LockSlot.INSTANCE;
   NoClip noClip = NoClip.INSTANCE;
   NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
   Nuker nuker = Nuker.INSTANCE;
   NoPush noPush = NoPush.INSTANCE;
   NoVelocity noVelocity = NoVelocity.INSTANCE;
   NoVignette noVignette = NoVignette.INSTANCE;
   NoControllerWeb noControllerWeb = NoControllerWeb.INSTANCE;
   NoWeb noWeb = NoWeb.INSTANCE;
   PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
   Particle particle = Particle.INSTANCE;
   PlayerFakeLags playerFakeLags = PlayerFakeLags.INSTANCE;
   Projectile projectile = Projectile.INSTANCE;
   FireworkESP fireworkESP = FireworkESP.INSTANCE;
   FastBreak fastBreak = FastBreak.INSTANCE;
   FastExp fastExp = FastExp.INSTANCE;
   Removals removals = Removals.INSTANCE;
   RPSpoofer rPSpoofer = RPSpoofer.INSTANCE;
   SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
   ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
   ShaderHands shaderHands = ShaderHands.INSTANCE;
   Satellite sattelite = Satellite.INSTANCE;
   ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
   Sonar sonar = Sonar.INSTANCE;
   Speed speed = Speed.INSTANCE;
   Sprint sprint = Sprint.INSTANCE;
   SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
   TargetESP targetESP = TargetESP.INSTANCE;
   TargetPearl targetPearl = TargetPearl.INSTANCE;
   Timer timer = Timer.INSTANCE;
   TotemAngel totemAngel = TotemAngel.INSTANCE;
   TpBack tpBack = TpBack.INSTANCE;
   TpsSync tpsSync = TpsSync.INSTANCE;
   TpLoot tpLoot = TpLoot.INSTANCE;
   ViewModel viewModel = ViewModel.INSTANCE;
   WorldTweaks worldTweaks = WorldTweaks.INSTANCE;
   XCarry xCarry = XCarry.INSTANCE;
   AutoSwap autoSwap = AutoSwap.INSTANCE;
   AimBot aimBot = AimBot.INSTANCE;
   TriggerBot triggerBot = TriggerBot.INSTANCE;
   NoSlow noSlow = NoSlow.INSTANCE;
   ScoreboardHP scoreboardHP = ScoreboardHP.INSTANCE;
   Step step = Step.INSTANCE;
   ServerHelper serverHelper = ServerHelper.INSTANCE;
   Spider spider = Spider.INSTANCE;
   LootTracker lootTracker = LootTracker.INSTANCE;
   HitMarker hitMarker = HitMarker.INSTANCE;
   Trails trails = Trails.INSTANCE;
   Trajectories trajectories = Trajectories.INSTANCE;
   BeautifulHands beautifulHands = BeautifulHands.INSTANCE;
   AutoBrew autoBrew = AutoBrew.INSTANCE;
}
